"""Initial migration

Revision ID: 470a057e1f2a
Revises: 
Create Date: 2026-02-01 10:10:18.026942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470a057e1f2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broken_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('root_service', sa.String(length=255), nullable=False),
    sa.Column('missing_services', sa.JSON(), nullable=True),
    sa.Column('total_spans', sa.Integer(), nullable=True),
    sa.Column('missing_span_count', sa.Integer(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broken_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broken_traces_analyzed_at'), ['analyzed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_broken_traces_root_service'), ['root_service'], unique=False)
        batch_op.create_index(batch_op.f('ix_broken_traces_trace_id'), ['trace_id'], unique=True)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('infrastructure_type', sa.String(length=50), nullable=True),
    sa.Column('is_customer_facing', sa.Boolean(), nullable=True),
    sa.Column('last_seen_catalog', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_service_name'), ['service_name'], unique=True)

    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('services_synced', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_jobs_job_type'), ['job_type'], unique=False)

    op.create_table('apm_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('has_apm', sa.Boolean(), nullable=False),
    sa.Column('apm_language', sa.String(length=50), nullable=True),
    sa.Column('last_seen_apm', sa.DateTime(), nullable=True),
    sa.Column('span_count_24h', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_name'], ['services.service_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apm_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apm_services_service_name'), ['service_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apm_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apm_services_service_name'))

    op.drop_table('apm_services')
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_jobs_job_type'))

    op.drop_table('sync_jobs')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_service_name'))

    op.drop_table('services')
    with op.batch_alter_table('broken_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broken_traces_trace_id'))
        batch_op.drop_index(batch_op.f('ix_broken_traces_root_service'))
        batch_op.drop_index(batch_op.f('ix_broken_traces_analyzed_at'))

    op.drop_table('broken_traces')
    # ### end Alembic commands ###
